name: Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1) Check out the repo
      - uses: actions/checkout@v3

      # 2) Install Buildozer + deps
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y zip openjdk-17-jdk python3-pip
          pip3 install --no-input buildozer==1.5.0 Cython==0.29.36

      # 3) Ensure binaries in assets/ are executable
      - name: chmod assets
        run: chmod +x assets/ffmpeg assets/yt-dlp_linux_aarch64

      # 4) Build release APK
      - name: Build APK
        run: buildozer -v android release

      # 5) Upload result as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3.2.1
        with:
          name: yt-trimmer-apk
          path: bin/*release.apk
