name: Android APK

# 👇 allow the runner to pull down third-party actions
permissions:
  contents: read
  actions: read

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y zip openjdk-17-jdk python3-pip
          pip3 install --no-input buildozer==1.5.0 Cython==0.29.36

      - name: chmod assets
        run: chmod +x assets/ffmpeg assets/yt-dlp_linux_aarch64

      - name: Build APK
        run: buildozer -v android release

      - name: Upload APK
        # pin to a concrete v3.x that definitely exists
        uses: actions/upload-artifact@v3.0.0
        with:
          name: yt-trimmer-apk
          path: bin/*release.apk
