name: Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: read  # required for checkout
      packages: write # required for upload-artifact

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4       # ← v4 is latest & signed by GitHub

    - name: Install system deps
      run: |
        sudo apt update
        sudo apt install -y zip openjdk-17-jdk python3-pip
        pip3 install --no-input buildozer==1.5.0 Cython==0.29.36

    - name: Build APK
      run: |
        buildozer -v android release

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: yt-trimmer-apk
        path: bin/*release.apk
