name: Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1) Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Install Buildozer + system deps
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip openjdk-17-jdk python3-pip
          pip3 install --no-input buildozer==1.5.0 Cython==0.29.36

      # 3) Pre-install & accept SDK build-tools licenses
      - name: Install & accept Android SDK Build-Tools
        run: |
          # Point to the sdkmanager that p4a will use
          SDKMANAGER="$HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager"
          # Install the specific build-tools version your spec asks for
          yes | $SDKMANAGER "build-tools;36.0.0" "platforms;android-33" || true
          # Accept all licenses
          yes | $SDKMANAGER --licenses || true

      # 4) Make your bundled binaries executable
      - name: Make assets executable
        run: chmod +x assets/ffmpeg assets/yt-dlp_linux_aarch64

      # 5) Build the release APK
      - name: Build Android APK
        run: buildozer -v android release

      # 6) Create a draft GitHub Release
      - name: Create Release
        id: release
        uses: actions/create-release@v1
        with:
          tag_name: apk-${{ github.run_number }}
          release_name: APK build ${{ github.run_number }}
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 7) Upload the APK to that Release
      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: bin/*release.apk
          asset_name: yt-trimmer.apk
          asset_content_type: application/vnd.android.package-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
