name: Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1) Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Install Buildozer + system deps
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip openjdk-17-jdk python3-pip
          pip3 install --no-input buildozer==1.5.0 Cython==0.29.36

      # 3) Make your bundled binaries executable
      - name: Make assets executable
        run: chmod +x assets/ffmpeg assets/yt-dlp_linux_aarch64

      # 4) Build the release APK
      - name: Build Android APK
        run: buildozer -v android release

      # 5) Upload the APK as an artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: yt-trimmer-apk
          path: bin/*release.apk
