name: Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip openjdk-17-jdk python3-pip
        pip3 install --no-input buildozer==1.5.0 Cython==0.29.36

    - name: Build APK
      run: |
        buildozer android clean
        buildozer android release

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: yt-trimmer-apk
        path: bin/*-release.apk
