name: Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      ANDROID_SDK_ROOT: $HOME/android-sdk
      ANDROID_HOME:    $HOME/android-sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y zip unzip python3-pip
          pip3 install --no-input buildozer==1.5.0 Cython==0.29.36

      - name: Setup Android SDK
        run: |
          SDK="$HOME/android-sdk"
          mkdir -p "$SDK/cmdline-tools"
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o cmdline-tools.zip
          unzip -q cmdline-tools.zip -d "$SDK/cmdline-tools"
          mv "$SDK/cmdline-tools/cmdline-tools" "$SDK/cmdline-tools/latest"
          mkdir -p "$SDK/tools/bin"
          ln -sf "$SDK/cmdline-tools/latest/bin/sdkmanager" "$SDK/tools/bin/sdkmanager"
          yes | "$SDK/tools/bin/sdkmanager" --sdk_root="$SDK" "platform-tools" "platforms;android-33" "build-tools;36.0.0"
          yes | "$SDK/tools/bin/sdkmanager" --sdk_root="$SDK" --licenses

      - name: Make assets executable
        run: chmod +x assets/ffmpeg assets/yt-dlp_linux_aarch64

      - name: Build Android APK
        run: buildozer -v android release
        env:
          ANDROID_SDK_ROOT: $HOME/android-sdk
          ANDROID_HOME:    $HOME/android-sdk

      - name: Debug: list bin/
        run: |
          echo "Listing contents of bin/:"
          ls -lah bin || echo "bin/ not found!"

      - name: Create Release
        id: release
        uses: actions/create-release@v1
        with:
          tag_name:     apk-${{ github.run_number }}
          release_name: APK build ${{ github.run_number }}
          draft:        true
          prerelease:   false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url:         ${{ steps.release.outputs.upload_url }}
          asset_path:         bin/*.apk
          asset_name:         yt-trimmer.apk
          asset_content_type: application/vnd.android.package-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
