Current runner version: '2.324.0'
Runner Image Provisioner
  Hosted Compute Agent
  Version: 20250508.323
  Commit: 81b259f29879f73b4213d199e42d8c3465dae986
  Build Date: 2025-05-08T19:40:08Z
Operating System
  Ubuntu
  22.04.5
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20250511.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20250511.1/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20250511.1
GITHUB_TOKEN Permissions
  Actions: read
  Contents: read
  Metadata: read
  Packages: read
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download immutable action package 'actions/checkout@v3'
  Version: 3.6.0
  Digest: sha256:942562b9c7d4b1f2557f1da21f4d3eb4eb4fd01f2ad78b2a6e187d1b193e0a0f
  Source commit SHA: f43a0e5ff2bd294095638e18286ca9a3d1956744
Error: Missing download info for actions/upload-artifact@v2
